
package com.remedy.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HPD_IncidentInterface_Create_WSPortTypePortType", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HPDIncidentInterfaceCreateWSPortTypePortType {


    /**
     * 
     * @param serviceType
     * @param notes
     * @param categorizationTier1
     * @param categorizationTier2
     * @param reportedSource
     * @param categorizationTier3
     * @param serviceCIReconID
     * @param resolution
     * @param productName
     * @param workInfoAttachment1Data
     * @param statusReason
     * @param action
     * @param customerCompany
     * @param vendorOrganization
     * @param directContactFirstName
     * @param loginID
     * @param productCategorizationTier1
     * @param impact
     * @param productCategorizationTier3
     * @param productCategorizationTier2
     * @param workInfoSummary
     * @param templateID
     * @param vendorName
     * @param vendorGroup
     * @param lookupKeyword
     * @param workInfoSource
     * @param assignedSupportCompany
     * @param hpdCI
     * @param firstName
     * @param vendorAssigneeGroups
     * @param workInfoLocked
     * @param serviceCI
     * @param workInfoType
     * @param assignee
     * @param status
     * @param workInfoNotes
     * @param lastName
     * @param createRequest
     * @param hpdCIFormName
     * @param ciName
     * @param manufacturer
     * @param resolutionCategoryTier2
     * @param resolutionCategoryTier3
     * @param resolutionCategoryTier1
     * @param middleInitial
     * @param urgency
     * @param workInfoDate
     * @param closureProductCategoryTier2
     * @param department
     * @param closureProductCategoryTier3
     * @param closureProductCategoryTier1
     * @param summary
     * @param hpdCIReconID
     * @param workInfoAttachment1Name
     * @param assignedGroup
     * @param directContactMiddleInitial
     * @param assignedSupportOrganizationt
     * @param vendorGroupID
     * @param workInfoViewAccess
     * @param closureProductModelVersion
     * @param closureManufacturer
     * @param corporateID
     * @param closureProductName
     * @param workInfoAttachment1OrigSize
     * @param vendorTicketNumber
     * @param assignedGroupShiftName
     * @param productModelVersion
     * @param directContactLastName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelpDesk_Submit_Service", action = "urn:HPD_IncidentInterface_Create_WS1/HelpDesk_Submit_Service")
    @WebResult(name = "Incident_Number", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
    @RequestWrapper(localName = "HelpDesk_Submit_Service", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1", className = "com.remedy.client.InputMapping1")
    @ResponseWrapper(localName = "HelpDesk_Submit_ServiceResponse", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1", className = "com.remedy.client.OutputMapping1")
    public String helpDeskSubmitService(
            @WebParam(name = "Assigned_Group", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String assignedGroup,
            @WebParam(name = "Assigned_Group_Shift_Name", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String assignedGroupShiftName,
            @WebParam(name = "Assigned_Support_Company", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String assignedSupportCompany,
            @WebParam(name = "Assigned_Support_Organizationt", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String assignedSupportOrganizationt,
            @WebParam(name = "Assignee", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String assignee,
            @WebParam(name = "Categorization_Tier_1", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String categorizationTier1,
            @WebParam(name = "Categorization_Tier_2", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String categorizationTier2,
            @WebParam(name = "Categorization_Tier_3", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String categorizationTier3,
            @WebParam(name = "CI_Name", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String ciName,
            @WebParam(name = "Closure_Manufacturer", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String closureManufacturer,
            @WebParam(name = "Closure_Product_Category_Tier1", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String closureProductCategoryTier1,
            @WebParam(name = "Closure_Product_Category_Tier2", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String closureProductCategoryTier2,
            @WebParam(name = "Closure_Product_Category_Tier3", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String closureProductCategoryTier3,
            @WebParam(name = "Closure_Product_Model_Version", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String closureProductModelVersion,
            @WebParam(name = "Closure_Product_Name", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String closureProductName,
            @WebParam(name = "Department", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String department,
            @WebParam(name = "First_Name", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String firstName,
            @WebParam(name = "Impact", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String impact,
            @WebParam(name = "Last_Name", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String lastName,
            @WebParam(name = "Lookup_Keyword", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String lookupKeyword,
            @WebParam(name = "Manufacturer", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String manufacturer,
            @WebParam(name = "Product_Categorization_Tier_1", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String productCategorizationTier1,
            @WebParam(name = "Product_Categorization_Tier_2", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String productCategorizationTier2,
            @WebParam(name = "Product_Categorization_Tier_3", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String productCategorizationTier3,
            @WebParam(name = "Product_Model_Version", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String productModelVersion,
            @WebParam(name = "Product_Name", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String productName,
            @WebParam(name = "Reported_Source", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    ReportedSourceType reportedSource,
            @WebParam(name = "Resolution", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String resolution,
            @WebParam(name = "Resolution_Category_Tier_1", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String resolutionCategoryTier1,
            @WebParam(name = "Resolution_Category_Tier_2", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String resolutionCategoryTier2,
            @WebParam(name = "Resolution_Category_Tier_3", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String resolutionCategoryTier3,
            @WebParam(name = "Service_Type", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    ServiceTypeType serviceType,
            @WebParam(name = "Status", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    StatusType status,
            @WebParam(name = "Action", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String action,
            @WebParam(name = "Create_Request", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    CreateRequestType createRequest,
            @WebParam(name = "Summary", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String summary,
            @WebParam(name = "Notes", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String notes,
            @WebParam(name = "Urgency", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String urgency,
            @WebParam(name = "Work_Info_Summary", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String workInfoSummary,
            @WebParam(name = "Work_Info_Notes", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String workInfoNotes,
            @WebParam(name = "Work_Info_Type", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    WorkInfoTypeType workInfoType,
            @WebParam(name = "Work_Info_Date", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String workInfoDate,
            @WebParam(name = "Work_Info_Source", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    WorkInfoSourceType workInfoSource,
            @WebParam(name = "Work_Info_Locked", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    CreateRequestType workInfoLocked,
            @WebParam(name = "Work_Info_View_Access", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    WorkInfoViewAccessType workInfoViewAccess,
            @WebParam(name = "Middle_Initial", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String middleInitial,
            @WebParam(name = "Status_Reason", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    StatusReasonType statusReason,
            @WebParam(name = "Direct_Contact_First_Name", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String directContactFirstName,
            @WebParam(name = "Direct_Contact_Middle_Initial", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String directContactMiddleInitial,
            @WebParam(name = "Direct_Contact_Last_Name", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String directContactLastName,
            @WebParam(name = "TemplateID", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String templateID,
            @WebParam(name = "ServiceCI", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String serviceCI,
            @WebParam(name = "ServiceCI_ReconID", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String serviceCIReconID,
            @WebParam(name = "HPD_CI", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String hpdCI,
            @WebParam(name = "HPD_CI_ReconID", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String hpdCIReconID,
            @WebParam(name = "HPD_CI_FormName", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String hpdCIFormName,
            @WebParam(name = "WorkInfoAttachment1Name", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String workInfoAttachment1Name,
            @WebParam(name = "WorkInfoAttachment1Data", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    byte[] workInfoAttachment1Data,
            @WebParam(name = "WorkInfoAttachment1OrigSize", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    Integer workInfoAttachment1OrigSize,
            @WebParam(name = "Login_ID", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String loginID,
            @WebParam(name = "Customer_Company", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String customerCompany,
            @WebParam(name = "Corporate_ID", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String corporateID,
            @WebParam(name = "Vendor_Name", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String vendorName,
            @WebParam(name = "Vendor_Organization", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String vendorOrganization,
            @WebParam(name = "Vendor_Group", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String vendorGroup,
            @WebParam(name = "Vendor_Group_ID", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String vendorGroupID,
            @WebParam(name = "Vendor_Assignee_Groups", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String vendorAssigneeGroups,
            @WebParam(name = "Vendor_Ticket_number", targetNamespace = "urn:HPD_IncidentInterface_Create_WS1")
                    String vendorTicketNumber);

}
